### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by sebastianhaas** [EruantalonJS/node-doxygen#16]
`npm install --save doxygen` fails on my system. I guess this is due to the `bin` configuration in your `package.json` which points to a file that doesn't exist.

 If you install using `npm install --save doxygen --no-bin-links` everything works fine since npm doesn't try to link a binary to the non-existing file.

**Comment by EruantalonJS** [comment]
Good catch, I was playing around with CLI options and missed removing the bin from the package.json

This is fixed now
