### ISSUE TITLE
add distRoute to `downloadVersion` function

### ISSUE THREAD

**Issue by nrgapple** [EruantalonJS/node-doxygen#33]
```js
function downloadVersion(distRoute, version, protocol, hostName, fileRoute)
```

add distRoute to the args so that the version can be downloaded somewhere outside of the node_modules dir

**Comment by EruantalonJS** [comment]
Won't fix - The option exists to install the tool globally (with npm install -g)

Copying the content to an arbitrary folder would be easy to do but difficult to mantain and would add no value over global install.
