### ISSUE TITLE
Is this running ok in OSX?

### ISSUE THREAD

**Issue by panitw** [EruantalonJS/node-doxygen#6]
I looked at the versionModule and it seems "darwin" hasn't been handled.

**Comment by EruantalonJS** [comment]
No, osx support is still on hold.

I will update this issue with the plans for OSX support, I will be working on it this week

**Comment by panitw** [comment]
👍 

Thanks @EruantalonJS I don't have any rush, take your time :)

**Comment by EruantalonJS** [comment]
Hi @panitw 

With version 0.1.2, this module includes OSX support :).

Closing the issue

**Comment by panitw** [comment]
That's cool, thanks!
